### ISSUE TITLE
Please release Remove dependency on timespan (#1014)

### ISSUE THREAD

**Issue by lukasoppermann** [foreversd/forever#1016]
Which resolves one of the security issues reported by snyk. Thanks.

**Comment by jpgcode** [comment]
I see the change applied to master branch, but the tag with the release is not created hence the version in npm is still with the module, when do this will be released?

**Comment by kibertoad** [comment]
There's a good chance there'll be a release on Monday.

**Comment by mvegacr** [comment]
Hi!

I'm getting the same error and I think that is because it's not on npm yet.

Is it going to be available anytime soon?

Thanks!

**Comment by kibertoad** [comment]
@indexzero Could you please provide me with npm publish permissions so that I could do the release and unblock everyone waiting for it?..

**Comment by kibertoad** [comment]
This was released in 1.0.0
