### ISSUE TITLE
When starting forever after boot with systemd service no forever proess is running.

### ISSUE THREAD

**Issue by JonasKappa** [foreversd/forever#1036]
I have the following problem:

I have a `startbot.timer`, a `startbot.service` and a `startbot` script (bash).
The `startbot.timer` says, that after reboot via `OnBootSec=1m`, that the `startbot.service` file should be executed one minute after booting. 
The `startbot.service` says `ExecStart=/bin/bash /usr/local/bin/startbot`.
The startbot script looks as following (after several tries):
```
su - alarm -c "cd ./projectfolder/anotherfolder; forever start index.js"
```
The first attempt was
```
cd /home/alarm/projectfolder/anotherfolder
forever start indexjs
```
The second would probably be enough, but I tried some different stuff.
When I run the script via command line: 
```
[alarm@alarm ~]$ /usr/local/bin/startbot
```
everything works as expected.
However, when I reboot the raspberry pi (with an arch linux distro -> need this for 64bit OS) no forever process is running.
When I check what happend with the service I type:
```
[alarm@alarm ~]$ systemctl status startbot.service
```
This says, that all worked fine and the service terminated with code: SUCCEED.
Also the output says: 
```
* startbot.service - starts the startbot script
    Loaded: loaded (/etc/systemd/system/startbot.service; static; vendor preset: disabled)
    Active: inactive (dead) since Fri 2019-08-30 08:58:16 CEST; 54s ago
   Process: 507 ExecStart=/bin/bash /usr/local/bin/startbot (code=exited, status=0/SUCCESS)
  Main PID: 507 (code=exited, status=0/SUCCESS)

Aug 30 08:58:10 alarm systemd[1]: Started starts the startbot script
Aug 30 08:58:10 alarm su[508]: (to alarm) root on none
Aug 30 08:58:10 alarm su[508]: pam_unix(su-l: session): session opened for user alarm by (uid=0)
Aug 30 08:58:16 alarm bash[507]: warn:        --minUptime not set, Defaulting to: 1000ms
Aug 30 08:58:16 alarm bash[507]: warn:        --spinSleepTime not set. Your scripts will exit if it does not stay up for at least 1000ms
Aug 30 08:58:16 alarm bash[507]: info:        Forever processing file: index.js
Aug 30 08:58:16 alarm su[508]: pam_unix(su-l: session): session closed for user alarm
Aug 30 08:58:16 alarm systemd[1]: startbot.service: Succeeded.
```

Then, when I type `forever list` it just says no process is running and the server is also not running. So its no problem just with forever list, as often mentioned in other Issues here.

also when trying the script as root like:
```
[root@alarm alarm]# /bin/bash /usr/local/bin/startbot
```
Everything thing works just fine and as expected, only when executing the scipt after reboot via systemd won't work.

**Comment by zubairfazal** [comment]
I would recommend using pm2

**Comment by TrueRushHunt3r** [comment]
> I would recommend using pm2

Yes, I switched to pm2 and also to ubuntu arm, because the network module of arch arm wasnt working after an update. So maybe I should close this issue.
