### ISSUE TITLE
Dependency Update Please

### ISSUE THREAD

**Issue by mlisonek98** [foreversd/forever#1042]
yo! anyway this can be updated?? It would be much appreciated!     

                === npm audit security report ===                        
                                                                                

                               Manual Review                                 
│            Some vulnerabilities require your attention to resolve            
│         Visit https://go.npm.me/audit-guide for additional guidance   

│ Low           │ Regular Expression Denial of Service                         │
│ Package       │ braces                                                       │
│ Patched in    │ >=2.3.1                                                      │
│ Dependency of │ forever                                                      │
│ Path          │ forever > forever-monitor > chokidar > anymatch > micromatch │
│               │ > braces                                                     │
│ More info     │ https://nodesecurity.io/advisories/786

**Comment by zubairfazal** [comment]
I would recommend using pm2

**Comment by kibertoad** [comment]
@mlisonek98 Fixed in forever@2.0.0
