### ISSUE TITLE
forever is dead. Everyone using it, please consider sunsetting its usage in your systems

### ISSUE THREAD

**Issue by kibertoad** [foreversd/forever#1046]
Unfortunately, at this point problem is not the lack of maintainers. Creator of this library does not trust anyone other than himself to publish new version of the library, and unfortunately he doesn't have any time for the project anymore, and that makes any changes done on the repository meaningless. His position is understandable, since forever is used for running huge amount of mission-critical production systems, but this leaves no path forward for the project, unfortunately.
For all intents and purposes `forever` should be considered dead, and you are much better off migrating to anything else, such as `pm2` or `nodemon`.

**Comment by indexzero** [comment]
`forever` is not dead. If I've been difficult to reach please accept my apologies – unfortunately I cannot discuss why but one day soon I hope to share what has been taking up the bulk of my time the last few years. It's quite personal and prolonged. 

Until then thanks for trying to help here @kibertoad, but again, I assure you – this project is not dead.

**Comment by kibertoad** [comment]
aaaaand the development is back on track again!
