### ISSUE TITLE
I can't run the application - Windows 2016 Server

### ISSUE THREAD

**Issue by TakiTamSlu** [foreversd/forever#1055]
**forever start bot.js**

`'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
error: Forever detected script exited with code: 1`

**Comment by kibertoad** [comment]
@TakiTamSlu Looks like some part of your path is not escaped somewhere, and path to something gets cut. Doesn't look like `forever` issue, but if you provided reproduction steps, we could look into it.

**Comment by nomi9995** [comment]
same issue @kibertoad I have checked there is not space in path. I am also on window server
