### ISSUE TITLE
forever@2.0.0 can't execute nodist node commands, but forever@1.0.1 can.

### ISSUE THREAD

**Issue by Skullpluggery** [foreversd/forever#1061]
I have a .bat file in Windows 10 which contains a script to run two Node applications with forever. It does work in forever@1.0.1 but it doesn't in forever@2.0.0 after I updated. I have tried clean install (removing all file traces of forever) and still no luck.

.bat command:
`forever start ./ez-dbcompare/server/bin/www & forever start ./ez-search/app.js --prod`

Log output:
`'C:\Program' is not recognized as an internal or external command, operable program or batch file`

Reverting to  forever@1.0.1 fix the problem. 

Others:
I use Nodist - Node Version Manager.

**Comment by kibertoad** [comment]
Thank you for reporting this. I'll take a look over weekend.

**Comment by nomi9995** [comment]
same issue

**Comment by nomi9995** [comment]
forever@1.0.0 is working for me

**Comment by vegeta897** [comment]
Same issue running node with bat files here on Windows 10, `forever@2.0.0`
No issues on `1.0.1`

**Comment by kibertoad** [comment]
@vegeta897 @Skullpluggery Can you try forever 3.0.0?

**Comment by vegeta897** [comment]
> Can you try forever 3.0.0?

It appears to be working! Thank you!
