### ISSUE TITLE
When calling forever app, node.exe pop up and it will not be closed

### ISSUE THREAD

**Issue by rahabchung** [foreversd/forever#1078]
When calling forever a node.exe pop up appear and it will not be closed. It happens in my new computer.

How to replicate:
Windows Server 2016 standard 64 bit
nodejs installed @ C:\Program Files (x86)\nodejs

When I call 'forever start app.js' command, a console popup which header is 'C:\PROGRA~2\nodejs\node.exe C:\myapp\app.js' appeared, this popup will never be closed unless I click the 'X' button on top right.

But when I open in my old computer:

Windows 7 standard 64 bit
nodejs installed @ C:\Program Files\nodejs
When I call 'forever start app.js', no popup will appear

Is that becasue I installed the nodejs @ wrong directory or because of powershell or another reason?
And this will not happen if I just call 'node app.js' command in both computers without using forever

**Comment by kibertoad** [comment]
I think I know the reason. Will try to publish a fix tonight.

**Comment by rahabchung** [comment]
> I think I know the reason. Will try to publish a fix tonight.

kibertoad, I am still looking forward to have your fix, thanks a lot!

**Comment by kibertoad** [comment]
@rahabchung Sorry for the delay. Could you please try forever 3.0.0?

**Comment by rahabchung** [comment]
> @rahabchung Sorry for the delay. Could you please try forever 3.0.0?

Works fine now, thanks a lot kibertoad!
