### ISSUE TITLE
CLI not finding script

### ISSUE THREAD

**Issue by nmcclay** [foreversd/forever#108]
Attempting to start forever I get the following:

<pre>
BlahBlah:node-api user$ forever start src/api.js 
info:   Running action: start
info:   Forever processing file: start
error:  Cannot start forever
error:  script /Users/Me/Documents/storage/dev/web/node-api/start does not exist.
</pre>

Inside /bin/forever this file is determined with

<pre>
var file = argv._[0]
</pre>

When I change the index to 1 this finds the file argument correctly.  If this has changed it doesn't match the CLI help's usage and example reference.

**Comment by marksherman** [comment]
Message from the future: this error comes up whenever you give an unknown action command to forever, like `forever log` which isn't a thing (clearly meant `forever logs`).
