### ISSUE TITLE
Unexpected identifier Forever 3.0.0

### ISSUE THREAD

**Issue by hanzou89** [foreversd/forever#1085]
npm install forever
`forever@3.0.0 node_modules/forever
├── object-assign@4.1.1
├── clone@2.1.2
├── colors@0.6.2
├── mkdirp@0.5.5 (minimist@1.2.5)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── nssocket@0.6.0 (eventemitter2@0.4.14, lazy@1.0.11)
├── shush@1.0.0 (strip-json-comments@0.1.3, caller@0.0.1)
├── utile@0.3.0 (deep-equal@0.2.2, ncp@1.0.1, i@0.3.6, async@0.9.2, rimraf@2.7.1)
├── cliff@0.1.10 (eyes@0.1.8, colors@1.0.3)
├── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.10, eyes@0.1.8, isstream@0.1.2, async@0.2.10, pkginfo@0.3.1)
├── prettyjson@1.2.1 (colors@1.4.0)
├── nconf@0.10.0 (ini@1.3.5, secure-keys@1.0.0, yargs@3.32.0)
├── flatiron@0.4.3 (optimist@0.6.0, director@1.2.7, prompt@0.2.14, broadway@0.3.6)
├── forever-monitor@3.0.0 (minimatch@3.0.4, ps-tree@0.0.3, broadway@0.3.6, chokidar@2.1.8)
└── deep-equal@1.1.1 (is-arguments@1.0.4, is-date-object@1.0.2, object-keys@1.1.1, is-regex@1.0.5, regexp.prototype.flags@1.3.0, object-is@1.1.2)`
Exception
`/usr/local/lib/node_modules/forever/lib/forever.js:71
  let sockets;
      ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/forever/bin/forever:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`
Node Version
`v0.10.29`
NPM Version
`1.4.21`

**Comment by kibertoad** [comment]
@hanzou89 Node 0.10 is no longer supported, please use older versions of forever.

**Comment by hanzou89** [comment]
@kibertoad Thank you for your fast reply. I will use another version.

**Comment by yboujraf** [comment]
Dear @kibertoad , @hanzou89 

I have same issue. 
I solved my issue by sing version : 0.15.3

Pls let me know if other versions could be used.
Best Regards
