### ISSUE TITLE
Preserve environment when restarting

### ISSUE THREAD

**Issue by simenbrekken** [foreversd/forever#116]
I've just encountered this in production where I'd first start a server with `NODE_ENV=production forever start myapp.js` and later attempt to restart it using `forever restart myapp.js` which would result in my restarted server being in development mode.

Perhaps it would be best if the environment each process was started with gets restored when restarting?

**Comment by woozyking** [comment]
:+1: to @Californian 

Or simply allow refreshing env vars on `forever restart`

**Comment by maaaikoool** [comment]
+1 to @Californian
