### ISSUE TITLE
var cwd = process.cwd();  Error: No such file or directory

### ISSUE THREAD

**Issue by nodesocket** [foreversd/forever#200]
We are seeing this following behavior often with forever.

When starting an app, the following is logged to the error log over and over again:

```
 node.js:289
      var cwd = process.cwd();
                  ^
 Error: No such file or directory
      at Function.resolveArgv0 (node.js:289:23)
      at startup (node.js:43:13)
      at node.js:448:3
```

We are running `node 4.1.2` and `forever 0.7.5`. Forever is instantiated like:

```
    //Setup spawn child
    var child = new(forever.Monitor)(torqueObject.start, {
        silent: true,
        forever: true,
        watch: false,
        sourceDir: "/nodesocket/gears/" + gear,
        outFile: "/nodesocket/gears/" + gear + "/logs/output.log",
        errFile: "/nodesocket/gears/" + gear + "/logs/error.log",
        logFile: "/nodesocket/gears/" + gear + "/logs/forever.log",
        pidFile: "/etc/nodesocket/lever/pids",
        options: torqueObject.parameters,
        minUptime: 2000,
        spinSleepTime: 1000,
        killTree: true,
        env: torqueObject.env
    });

    //Acutally spawn child
    child.start();
```

Obviously its trying to get the current working directory, but failing. Any idea what specific code in forever is calling `process.cwd()`.

**Comment by julienetie** [comment]
@geoyws Great, that worked for me, thanks. (All I had to do was cd to no directory)

**Comment by stefangrund** [comment]
For me, too. Thanks @geoyws.

**Comment by yakkub5** [comment]
Thanks a lot, @geoyws.

**Comment by webexpert4rv** [comment]
Me too :)

**Comment by xtfer** [comment]
Very good @geoyws

**Comment by leonlo** [comment]
Thanks, @geoyws

**Comment by bke-daniel** [comment]
@geoyws You deserve a drin, Sir! (y)

**Comment by go299** [comment]
Thanks

**Comment by shrikantr-webonise** [comment]
Thanks, @geoyws!

**Comment by Schemata** [comment]
in iTerm right click in the terminal window and choose 'restart'.
Thanks @geoyws

**Comment by jermainedilao** [comment]
thanks @geoyws !

**Comment by michaelchadwick** [comment]
That seemed to work, @geoyws! What does installing the "n" package do, thought? Could it be any package?

**Comment by regiondavid** [comment]
Using this command in the same terminal fix my error.

**Comment by JapoDeveloper** [comment]
Thanks @geoyws your solution solved my problem.

**Comment by mxdi9i7** [comment]
My problem was solved by closing the terminal and navigate into the project root again to start the app. I think my issue was caused by checking out a branch that that doesn't have the project directory in it to run the app.

**Comment by sravanpabolu** [comment]
tanks @mxdi9i7 . restarting terminal solved the issue

**Comment by xixiyang1216** [comment]
thanks@mxdi9i7

**Comment by zgr024** [comment]
Just restart terminal

If you want you can `run sudo npm cache clean` -f but not necessary.

**Comment by YongLAGCC** [comment]
> My problem was solved by closing the terminal and navigate into the project root again to start the app. I think my issue was caused by checking out a branch that that doesn't have the project directory in it to run the app.

Thanks, it works like what you said.

**Comment by YongLAGCC** [comment]
I uninstalled and updated yarn, 

with a new error: 
Aborting installation.
  yarnpkg add --exact react react-dom react-scripts --cwd /Users/myrepository/MERN_SHOPPING_LIST/client/shopping has failed.

then I do:  
$ npm cache clean --force
$ create-react-app cool-projecy-name

works for me.

**Comment by elalealvaro** [comment]
Thanks @geoyws ! 👏

**Comment by ddebasilio** [comment]
For anyone still having this issue in 2019, if it is inside a docker container, removing the container and forcing a recreation fixes thi issue.

**Comment by parthvadhadiya** [comment]
which IDE are you using, in my case if I checkout in another branch which does not have a perticuler folder or file, then I came back to the original branch. it does not find a proper path for running js code. 
solution for me. I will go back to the main project folder with cd command and then come back to the execution path and everything is sorted.

**Comment by ryuchaehwa** [comment]
@geoyws Super Thanks :) I didn't run the commands but closed terminal and opened it again. works perfect. :) 

@whomever-might-have-similar-issue
I'm testing it on CentOS Linux node version. I didn't have this problem before but now for the other server, I have this issue.
Seems like system couldn't find the npm path correctly if you don't restart you putty or whatever for the other users.

1. installed npm linux version and works perfect (node -v, npm -v)
2. logout, login with other user but only node -v works, and get this error when run 'npm -v' command
3. restarted putty.
4. works perfect.
