### ISSUE TITLE
npm install forever -g fails

### ISSUE THREAD

**Issue by guyht** [foreversd/forever#201]
```
% node -v
v0.6.6

% npm -v
1.0.106
```

npm install forever -g 
npm WARN watch@0.4.0 package.json: bugs['web'] should probably be bugs['url']

> daemon@0.3.2 preinstall /usr/local/lib/node_modules/forever/node_modules/daemon
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.033s)
Waf: Entering directory `/usr/local/lib/node_modules/forever/node_modules/daemon/build'
[1/2] cxx: src/daemon.cc -> build/Release/src/daemon_1.o
[2/2] cxx_link: build/Release/src/daemon_1.o -> build/Release/daemon.node
Waf: Leaving directory`/usr/local/lib/node_modules/forever/node_modules/daemon/build'
'build' finished successfully (0.435s)
npm ERR! Failed unpacking /home/ubuntu/.npm/socket.io/0.6.18/package.tgz
npm ERR! error installing socket.io@0.6.18 Error: `tar "-zmvxpf" "/home/ubuntu/.npm/socket.io/0.6.18/package.tgz" "-o"`
npm ERR! error installing socket.io@0.6.18 failed with 2
npm ERR! error installing socket.io@0.6.18     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR! error installing socket.io@0.6.18     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing socket.io@0.6.18     at maybeExit (child_process.js:359:16)
npm ERR! error installing socket.io@0.6.18     at Socket.<anonymous> (child_process.js:464:7)
npm ERR! error installing socket.io@0.6.18     at Socket.emit (events.js:67:17)
npm ERR! error installing socket.io@0.6.18     at Array.0 (net.js:314:10)
npm ERR! error installing socket.io@0.6.18     at EventEmitter._tickCallback (node.js:192:40)
npm ERR! error installing dnode@0.8.2 Error: `tar "-zmvxpf" "/home/ubuntu/.npm/socket.io/0.6.18/package.tgz" "-o"`
npm ERR! error installing dnode@0.8.2 failed with 2
npm ERR! error installing dnode@0.8.2     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR! error installing dnode@0.8.2     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing dnode@0.8.2     at maybeExit (child_process.js:359:16)
npm ERR! error installing dnode@0.8.2     at Socket.<anonymous> (child_process.js:464:7)
npm ERR! error installing dnode@0.8.2     at Socket.emit (events.js:67:17)
npm ERR! error installing dnode@0.8.2     at Array.0 (net.js:314:10)
npm ERR! error installing dnode@0.8.2     at EventEmitter._tickCallback (node.js:192:40)
npm WARN eventemitter2@0.4.1 package.json: 'contributers' should probably be 'contributors'
npm ERR! error rolling back dnode@0.8.2 Error: UNKNOWN, unknown error '/usr/local/lib/node_modules/forever/node_modules/dnode/node_modules'
npm ERR! error installing forever@0.7.5 Error: `tar "-zmvxpf" "/home/ubuntu/.npm/socket.io/0.6.18/package.tgz" "-o"`
npm ERR! error installing forever@0.7.5 failed with 2
npm ERR! error installing forever@0.7.5     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR! error installing forever@0.7.5     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing forever@0.7.5     at maybeExit (child_process.js:359:16)
npm ERR! error installing forever@0.7.5     at Socket.<anonymous> (child_process.js:464:7)
npm ERR! error installing forever@0.7.5     at Socket.emit (events.js:67:17)
npm ERR! error installing forever@0.7.5     at Array.0 (net.js:314:10)
npm ERR! error installing forever@0.7.5     at EventEmitter._tickCallback (node.js:192:40)
npm ERR! error installing ncp@0.2.3 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/utile/node_modules/ncp/bin/ncp'
npm ERR! error installing winston@0.5.9 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/clip/node_modules/prompt/node_modules/___winston.npm/package/README.md'
npm ERR! error installing event-stream@0.5.3 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/ps-tree/node_modules/parse-table/node_modules/___event-stream.npm/package/readme.markdown'
npm ERR! error installing prompt@0.1.11 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/clip/node_modules/prompt/node_modules/___winston.npm/package/README.md'
npm ERR! error installing eyes@0.1.7 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/clip/node_modules/winston/node_modules/___eyes.npm/package/README.md'
npm ERR! error installing parse-table@0.0.0 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/ps-tree/node_modules/parse-table/node_modules/___event-stream.npm/package/readme.markdown'
npm ERR! error installing loggly@0.3.10 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/clip/node_modules/winston/node_modules/___loggly.npm/package/README.md'
npm ERR! error installing broadway@0.1.5 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/flatiron/node_modules/broadway/package.json'
npm ERR! error installing winston@0.3.5 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/clip/node_modules/winston/node_modules/___eyes.npm/package/README.md'
npm ERR! error installing utile@0.0.10 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/utile/node_modules/ncp/bin/ncp'
npm ERR! error installing ps-tree@0.0.2 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/ps-tree/node_modules/parse-table/node_modules/___event-stream.npm/package/readme.markdown'
npm ERR! error installing flatiron@0.1.6 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/flatiron/node_modules/broadway/package.json'
npm ERR! error installing clip@0.1.6 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/clip/node_modules/winston/node_modules/___eyes.npm/package/README.md'
npm ERR! error rolling back forever@0.7.5 Error: UNKNOWN, unknown error '/usr/local/lib/node_modules/forever/node_modules/clip/node_modules/prompt/node_modules'
npm ERR! Error: `tar "-zmvxpf" "/home/ubuntu/.npm/socket.io/0.6.18/package.tgz" "-o"`
npm ERR! failed with 2
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:217:20)
npm ERR!     at ChildProcess.emit (events.js:70:17)
npm ERR!     at maybeExit (child_process.js:359:16)
npm ERR!     at Socket.<anonymous> (child_process.js:464:7)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR!     at Array.0 (net.js:314:10)
npm ERR!     at EventEmitter._tickCallback (node.js:192:40)
npm ERR! Report this _entire_ log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Linux 2.6.32-308-ec2
npm ERR! command "node" "/usr/local/bin/npm" "install" "forever" "-g"
npm ERR! cwd /vol/home/git_src/npm
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.0.106
npm WARN request@2.1.1 package.json: bugs['web'] should probably be bugs['url']
npm ERR! error installing winston@0.5.9 Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/forever/node_modules/winston/package.json'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /vol/home/git_src/npm/npm-debug.log
npm not ok`

**Comment by victorbiga** [comment]
The above fresh install did not work, managed to get it going with 
```
$sudo npm config set registry http://registry.npmjs.org/
```
