### ISSUE TITLE
forever@0.8.3 list doesn't show running processes with node@0.6.7

### ISSUE THREAD

**Issue by remoe** [foreversd/forever#225]
hi

when i start a process with "forever start process" and then it does not list this running process with "forever list".

I use node@0.6.7 and forever@0.8.3 and GENTOO. it was worked before with node@0.4.12 .

``` json
...
  "trace": [
    {
      "column": 31,
      "file": "/usr/lib64/node_modules/forever/lib/forever.js",
      "function": "Array.0",
      "line": 194,
      "method": "0",
      "native": false
    },
    {
      "column": 41,
      "file": "node.js",
      "function": "EventEmitter._tickCallback",
      "line": 192,
      "method": "_tickCallback",
      "native": false
    }
...

  "stack": [
    "Error: Cannot find forever process: undefined",
    "    at Array.0 (/usr/lib64/node_modules/forever/lib/forever.js:194:31)",
    "    at EventEmitter._tickCallback (node.js:192:41)"
  ],
  "level": "error",
  "message": "uncaughtException"

```

``` sh
/root/.forever/
|-- [-rw-r--r-- root    ]  NZTy.log
|-- [-rw-r--r-- root    ]  config.json
|-- [drwxr-xr-x root    ]  pids
|   `-- [-rw-r----- root    ]  NZTy.pid
`-- [drwxr-xr-x root    ]  sock
```

config.json

``` json

{
  "root": "/root/.forever",
  "pidPath": "/root/.forever/pids",
  "sockPath": "/root/.forever/sock",
  "loglength": 100,
  "columns": [
    "uid",
    "command",
    "script",
    "forever",
    "pid",
    "logfile",
    "uptime"
  ]
}
```

``` sh
forever@0.8.3 /usr/lib/node_modules/forever
├── watch@0.5.0
├── timespan@2.0.1
├── pkginfo@0.2.3
├── minimatch@0.0.5 (lru-cache@1.0.5)
├── portfinder@0.2.1 (mkdirp@0.0.7)
├── daemon@0.4.1
├── node-fork@0.2.2
├── utile@0.0.10 (rimraf@1.0.9 mkdirp@0.2.2 ncp@0.2.3 async@0.1.15)
├── optimist@0.2.8 (wordwrap@0.0.2)
├── nssocket@0.3.5 (lazy@1.0.7 eventemitter2@0.4.1)
├── cliff@0.1.5 (eyes@0.1.7 colors@0.6.0-1)
├── ps-tree@0.0.2 (parse-table@0.0.0)
├── broadway@0.1.5 (eventemitter2@0.4.1 nconf@0.5.0)
├── flatiron@0.1.6 (pkginfo@0.2.2 director@1.0.8 prompt@0.1.11)
├── nconf@0.5.1 (ini@1.0.2 async@0.1.15 optimist@0.3.1)
└── winston@0.5.9
```

Cheers
Remo

**Comment by santhu227** [comment]
Hi Guys.,,

**Comment by santhu227** [comment]
Hi Guys.,

I am badly stucked to run forever as linux service. If i try to run forever as linux service by logged in as user(not as root).

First I tried to run forever as command by user

If i try to run command as lsof | grep 25696(process id of forever)

it is giving log as by this it is starting the worker sock
node      25696     stapp    9r      DIR              253,0     4096        2 /
node      25696     stapp   10u     unix 0xffff8801385c9680      0t0 45772086 socket
node      25696     stapp   11u     unix 0xffff88013998acc0      0t0 45772026 /home/stapp/.forever/sock/worker.14295342786175T4.sock
node      25696     stapp   13u     unix 0xffff8801385c9c80      0t0 45772088 socket
node      25696     stapp   15u     unix 0xffff88013ca99380      0t0 45772090 socket


Same thing If i tried to run as linux service (/etc/init.d/myservice_file) if i check the log by 

 lsof | grep 25786(process id of forever)

it is giving log as by this it is not starting worker sock

node      25770     stapp    7w     FIFO                0,8      0t0 45773381 pipe
node      25770     stapp    8u      REG                0,9        0     3672 anon_inode
node      25770     stapp    9r      DIR              253,0     4096        2 /
node      25770     stapp   10u     unix 0xffff88013b5c9c80      0t0 45773384 socket
node      25770     stapp   12u     unix 0xffff88013b5c9680      0t0 45773386 socket
node      25770     stapp   14u     unix 0xffff88013b5c9080      0t0 45773388 socket


Please help me out.

In one word i can forever as linux init.d service by linux user (not root) it is not starting /home/user/.forever/sock/worker.1429535560073IJV.sock 

Regards
Samaka
