### ISSUE TITLE
Not writing log files in Ubuntu using -e -o

### ISSUE THREAD

**Issue by henryoswald** [foreversd/forever#228]
On my ubuntu server (11.10) forever isn't writing the log files as expected. Using the same setup in OS X it works perfectly, both systems are running node 0.6.7 and forever 0.8.4.

both the out and err files (-e -o) are created but never written to, however the forever log file does work ( -l )

a couple of times the ubuntu box also stopped listing the running processes as was common pre 0.6.x fix.

**Comment by LuisdelaVega** [comment]
+1

**Comment by johannesjo** [comment]
+1
