### ISSUE TITLE
Add --no-log option which disables all Logging.

### ISSUE THREAD

**Issue by mediaupstream** [foreversd/forever#326]
$ forever start server.js
info:   Forever processing file: server.js
error:  Cannot start forever
error:  log file ~/.forever/forever.log exists. Use the -a or --append option to append log

I would love to be able to run forever without logging anything, ever. something like:
$ forever start -n server.js

where -n would be --no-log "Forces forever to NOT log stuff"

Thoughts?

**Comment by lhyunh** [comment]
How can I ignore logs on Windows?
I can't use `forever start -a -l /dev/null server.js`
`forever start -a -l NUL server.js` is makes NUL file.

**Comment by adambuczynski** [comment]
@indexzero that doesn't work if you are running it on both windows or mac, and you want to have one json configuration file for the app. On mac/linux, you need to specify `/dev/null`, on windows, you need to specify `NUL`. How to accomplish that? I think a config param might be necessary.

**Comment by spryce** [comment]
The proposed solution doesnt seem to work at all in windows.

`forever start -a -l NUL server.js` simply results in a file named NUL that has no extension and grows as it is logged to. 

Right clicking the file shows zero bytes but closer inspection shows that it is in fact growing.

**Comment by dylanh724** [comment]
This is at the top of Google. Was this ever implemented? Found 90gb of freaking logs in .forever

**Comment by adamreisnz** [comment]
You're better off switching to pm2 like we did, it's actually maintained.
