### ISSUE TITLE
forever list shows `no forever processes running` on Windows

### ISSUE THREAD

**Issue by hbrls** [foreversd/forever#337]
I've seen related or duplicated issues, and all of which were fixed and closed.
But none of them was on windows.

I have fresh installed Windows 2008, node.js, forever.
and I got this issue:

```
.\forever start app.js   // functions well as expected
.\forever list  // no forever processes running
.\forever stop app.js // cannot find process with index: app.js
```

exactly the same symptom as [issue#224](https://github.com/nodejitsu/forever/issues/224) and etc.

**Comment by juanpasolano** [comment]
Same here on a Amazon EC2 Ubuntu
node@0.10.29
forever@0.13.0

**Comment by robcalcroft** [comment]
If you're running the forever command with sudo, this is what I think is breaking it. You can run `sudo bash -c 'forever start server.js'` which should run it in a root environment but not use the sudo command directly on forever

**Comment by syzer** [comment]
+1 on win7 x64
inside script:
```js
    var forever = require('forever');
    forever.restartAll(true);
```

```
error: Error: Cannot find forever process: undefined
    at node_modules\forever\lib\forever.js:204:31
    at node_modules\newrelic\node_modules\continuation-local-storage\node_modules\async-listener\glue.js:188:31
    at process._tickCallback (node.js:415:13)
```

**Comment by astw** [comment]
same issue

**Comment by astw** [comment]
in windows prompt, after forever start,  and type forever list in the same prompt window,  I can see the process,  but if I open another prompt window and type forever list,  it shows nothing

**Comment by rahilwazir** [comment]
I'm having the same issue in Windows no list shows
@indexzero  Is this resolved?

**Comment by vuongtran** [comment]
+1 same issue on CentOS

**Comment by AdamGerthel** [comment]
+1 on WIndows server 2012

**Comment by jagc** [comment]
End of 2015.. Err yeah, still same issue. Still doesn't work. Same error message showing.
Environment:
OS: Windows 7 ultimate x64
Node:       v.4.2.1
Forever:    v.0.15.1
Nodemon: 1.8.1

**Comment by developez** [comment]
I set a daemon in ubuntu in this way:

`start on startup
exec forever start /foo/foo.js`

The command `forever list` shows me no process with my user but it shows the process foo.js if doing "sudo" or enter as root using "su".

**Comment by Choko256** [comment]
the `config.json` in `.forever` is empty... here's the reason.

**Comment by SHASHANK-PRO-05** [comment]
linux users, check your memory guys might have been used up

**Comment by stefanofiorentino** [comment]
If you exec the `forever start app.js` within init.d you should later type `sudo HOME=/home/pi/devel/web-app -u root forever list` to have the correct list.

**Comment by MetalHeroZ** [comment]
> linux users, check your memory guys might have been used up

yeahh!
