### ISSUE TITLE
Forver will not install properly on Ubuntu 12.04 Server.

### ISSUE THREAD

**Issue by gaurav21r** [foreversd/forever#349]
The official documentation states that for installation we have to 

```
$ [sudo] npm install forever -g
```

I tried this on my Ubuntu 12.04 VPS via PUTTY, first I got an error like https://github.com/nodejitsu/forever/issues/282

Even after 

```
sudo apt-get install build-essential
```

it didn't work.

By changing the npm installation to

```
$ [sudo] npm install -g forever
```

It worked! Just wanted to share. Incase this is valid for other Linux distros as well request to change the official doc as well.

**Comment by encrypter-manyange** [comment]
npm WARN deprecated path-is-absolute@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
npm ERR! Linux 4.15.0-1057-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "forever"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by encrypter-manyange** [comment]
I am getting this error please help

**Comment by encrypter-manyange** [comment]
on sudo npm i -g forever

**Comment by TheBlockchainDeveloper** [comment]
You need to upgrade npm: 
> sudo npm install -g npm@latest 
Then: 
> sudo npm install -g forever
