### ISSUE TITLE
forever hangs executing actions

### ISSUE THREAD

**Issue by inolen** [foreversd/forever#370]
Chatted with coderarity in IRC earlier and he repro'd easily as well and asked I write up a report.

On node 0.9.5 (on Debian) I can start a script, however, every subsequent action (e.g. list, stopall) hangs indefinitely. 

I thought it was perhaps due to me running forever as non-root, however he ran into the same problems as root.

**Comment by iMoses** [comment]
I'm suffering from the same problem on Ubuntu 14.04, using Forever 0.14.1 on nodejs 0.10.25
Forever will hang on stop commands

**Comment by EwanValentine** [comment]
Getting the same thing. It's unusable.

**Comment by 1e4** [comment]
Just thought I would poke in and say I too have the same issue several years later on Ubuntu, I can run a script, but any other command simply hangs.

**Comment by odnarb** [comment]
It's 2020.. why is this still an issue?

**Comment by iMoses** [comment]
> It's 2020.. why is this still an issue?

I believe that if you are still using this library in 2020 you are definitely doing something wrong. The nodejs ecosystem has come a long way since then and this tool is pretty much obsolete when it comes to best practices in the industry, as well as effectivity as this issue suggests..

**Comment by kibertoad** [comment]
Yes. Please consider using pm2 or nodemon.
