### ISSUE TITLE
Forever list and forever restart server.js not working

### ISSUE THREAD

**Issue by lavinachitara** [foreversd/forever#378]
Hello,

I installed forever package from npm package manager

npm install forever -g

and successfully installed on my machine.

I started my server file by using below command :

forever start -l forever.log -o out.log -e err.log my-daemon.js

and its worked successfully

but when I tried to restart my node server and stop to node server which is not working

below all syntax I used :
1. forever start -l forever.log -o out.log -e err.log my-daemon.js ----> working
2. forever list ---> not working [showing no forever process running]
3. forever stop my-daemon.js ----> not working [no such process is running]

Please help me I have started my node server but I am not able to restart it.

I am using node version v0.8.15, forever version @0.10.0 on windows server

Thanks 
Lavina Chitara

**Comment by lokeshwebmobi** [comment]
forever stop index_of_process
