### ISSUE TITLE
Forever detected script exited with code: null

### ISSUE THREAD

**Issue by leostratus** [foreversd/forever#420]
Hey gang,

I have a simple CRUD app that I built with Node + Express. I'm using Forever to keep it rolling. Once in a while it will restart itself with:

Forever detected script exited with code: null

There is nothing in the logs prior to this exit that suggests what the problem could be. 

I understand that exiting with code 0 is all good, exiting with code 1 means there was a problem (and the logs have a dump of what went wrong/where the crash was) but 'null' does not provide me with any information at all. All the requests immediately preceding it seem to indicate business as usual.

Sad panda.

Can someone point me towards some clues?

**Comment by shlomisas** [comment]
+1

**Comment by EugeneKostrikov** [comment]
Seems like the issue is back. With no sign on any problem it just crashes logging "Forever detected script exited with code: null".

**Comment by vahpetr** [comment]
+1

mkdir ~/test
nano ~/test/server.js

var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');


nano /etc/init.d/remotedebug

### BEGIN INIT INFO
# Provides:          remotedebug
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RemoteDebug Node App
### END INIT INFO

directory=~/test
script=server.js

start(){
	forever -p ~/.foreve -a -l $directory/sys.log -e $directory/err.log -o $directory/out.log --sourceDir $directory start $script
}

stop(){
	forever stop $script
}

status(){
	forever list
}

restart(){
	forever restart $script
}

default(){
	echo "Usage: /etc/init.d/remotedebug {start|stop|status|restart}"
    exit 1
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    restart
    ;;
  *)
    default
    ;;
esac

exit 0


chmod 755 /etc/init.d/remotedebug
update-rc.d remotedebug defaults

/etc/init.d/remotedebug start
/etc/init.d/remotedebug stop

cat ~/test/err.log
error: Forever detected script exited with code: null

**Comment by duncandoo** [comment]
I've come across this error too. Mention above of possible problem with non-specified dependency.

In my case `forever start docpad` is fine initially but after `docpad install eco` it produces the message.

**Comment by alexey** [comment]
well, any possibility to debug it ?
i've added -o and -e  to start of forever but logs didnt have any valuable info, just:
```error: Forever detected script exited with code: null```

**Comment by MartinMelo** [comment]
I have the same issue with the 0.13.0 version

**Comment by aido179** [comment]
I've had the same issue.
Running `forever cleanlogs` before `forever start -l forever.log -o out.log -e err.log server.js` seems to be a quick fix, at least for me.

**Comment by bgSosh** [comment]
I'm getting this using v0.14.1 when doing a 'forever restart'.

**Comment by gabssnake** [comment]
Can also confirm it on v0.14.1 when running `forever stopall` or `forever restartall`
(node v0.12.0 on Debian)

**Comment by blacksonic** [comment]
It is easy to reproduce:
```
var forever = require('forever');

var monitor = forever.start('server/index.js', {});
monitor.on('start', function () {
  forever.startServer(monitor);
});

setTimeout(function() {
  forever.stop(monitor.childData.pid);
}, 1000);
```
I want to start forever for my build pipeline with e2e tests. Start the server with forever, run the e2e tests and then stop the server. Unfortunately it logs an error.
A dirty hack can be before stopping the process:
```
monitor.removeAllListeners('exit:code');
```

**Comment by mpenate** [comment]
+1 Same issue.

**Comment by ElegantScripting** [comment]
+1 Same issue.

**Comment by gregory-yet** [comment]
+1 Same issue 
```
error: Forever detected script was killed by signal: SIGKILL
```

**Comment by khanhankkhan** [comment]
forever start server.js 

used to work now the server won't start. Nothing is listening on port 3000 (which server.js is listening on), nginx is redirecting traffic from port 80 to 3000, idk why forever wont start my server anymore

**Comment by sleepdeprivation** [comment]
+1
Just thought I'd pile on

**Comment by davidemandrini** [comment]
I think the issue is due to changing files in the working directory.
C.f. http://stackoverflow.com/questions/32324973/nodejs-script-killed-by-sigkill-when-running-on-forever
