### ISSUE TITLE
forever under windows not supported?

### ISSUE THREAD

**Issue by daslicht** [foreversd/forever#422]
Hello,
I have just tried to run forever on a windows baased server, however when i try to start my app i get:

`````` PHP
D:\node\swig>forever app.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up f
or at least 1000ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:975:11)
    at Process.ChildProcess._handle.onexit (child_process.js:766:34)```

Any idea how to fix?
``````

**Comment by amrutraj** [comment]
I installed it using 
npm i -g forever

How did you get to work it as a windows native software? 
When I do 
C:\myapp\>forever app.js
'forever' is not recognized as an internal or external command,
operable program or batch file.
