### ISSUE TITLE
forever: command not found

### ISSUE THREAD

**Issue by mrbryo** [foreversd/forever#532]
Just installed tonight with out error but I did receive some warnings:

npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.24","npm":"1.3.21"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.24","npm":"1.3.21"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.24","npm":"1.3.21"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.24","npm":"1.3.21"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.24","npm":"1.3.21"})

To me I'm running a newer version than forever was looking for but I can only assume it will work…correct?

Here is the install command I used: sudo npm install forever -g

I did run the install a second time resulting in the same output.

I'm trying to set it to run Ghost using their suggested command line from the install directory: NODE_ENV=production forever start index.js

To me the command line seems wrong but the response I got with that command line is:

NODE_ENV=production: Command not found.

I expected an error but still i followed their direction.

So I tried: forever start index.js

OS Returned: forever: Command not found.

I'm on Mac OS 10.8.5

**Comment by vincentsordo** [comment]
For some reason the forever command was not added to my path so I had to reference the forever executable in the node_modules like so `node_modules/forever/bin/forever`.
