### ISSUE TITLE
What are all the columns?

### ISSUE THREAD

**Issue by dandv** [foreversd/forever#542]
> help:      columns add &lt;col>   Adds the specified column to the output in `forever list`
> help:      columns rm &lt;col>    Removed the specified column from the output in `forever list`
> help:      columns set &lt;cols>  Set all columns for the output in `forever list`

The README or `--help` should mention the available columns. Are there any beyond `uid`, `command`, `script`, `forever`, `pid`, `logfile`, and `uptime`?

**Comment by uptownhr** [comment]
what are the available columns?

**Comment by indexzero** [comment]
A PR to update the docs [against the code](https://github.com/foreverjs/forever/blob/master/lib/forever.js#L983-L1043) would be helpful.

**Comment by tolotrasamuel** [comment]
Was this issue been abandoned? It's 2019 and I don't find the answer

**Comment by tolotrasamuel** [comment]
https://github.com/foreverjs/forever/blob/0f609473a488eec3e46050687070cd92a9a05c34/lib/forever.js#L308

**Comment by kibertoad** [comment]
@tolotrasamuel My apologies. I am the last standing maintainer of `forever` (to the extent it could be maintained without being able to publish new versions on my own :D), and there are gazillion other projects I need to work on, hence progress is slow. Thank you for bringing attention to this issue, though, it doesn't sound too complicated to address, and special thank you for pointing the right place in code. I'll open a PR soonish.

**Comment by kibertoad** [comment]
@tolotrasamuel Please review #1029!
