### ISSUE TITLE
i have some problem with node V0.11.XX

### ISSUE THREAD

**Issue by lonso** [foreversd/forever#551]
i am run node in v0.11.XX and i use forever to run that.
i exec:  forever start -a -e erro.log -o out.log -l log.log app.js
then the console display:
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: app.js

forever not return, it still on ---> info:    Forever processing file: app.js  .
not return command line.

**Comment by samuelgbrown** [comment]
I'm experiencing this after upgrading to `0.12.2`. It seems my process has spawned and works (`forever list` shows it running, but forever never returns the command line. It's breaking my deployments because the script gets stuck in the foreground.
