### ISSUE TITLE
Support for npm scripts

### ISSUE THREAD

**Issue by appsforartists** [foreversd/forever#615]
In #540, @electerious asked about running a script with `npm start` and was told to use `-c`.  This is unfortunately not a foolproof solution: `forever start -c "npm start"` is not a valid command by itself; it needs a directory to start from.  That directory will then be passed as an arg to `npm start` (and to whatever script that calls).  This can break your app in weird ways when run with forever.

For instance, I have an app that runs a bunch of servers.  I can `npm start` to run them all, or `npm start serverName` to start a particular one.  If I try to `forever start -c "npm start" /home/me/Projects/app/`, my app tries to start a server named "`/home/me/Projects/app/`" and dies.

It would be awesome if there was an easy syntax to tell `forever` to parse and execute the scripts in `package.json`.  For instance:

```
forever --npm start /path/to/app/
```

could run 

```
cd /path/to/app/; npm start 
```

as a daemon.

**Comment by adius** [comment]
+1 for support for npm scripts

**Comment by axelg12** [comment]
+1

**Comment by xpepermint** [comment]
+1
