### ISSUE TITLE
npm ERR! Error: failed to fetch from registry: forever

### ISSUE THREAD

**Issue by LaakkoT** [foreversd/forever#618]
Hi,

I have been facing now for two days the same error when trying to install forever:

pi@raspberrypi / $ sudo npm install forever -g
npm http GET https://registry.npmjs.org/forever

npm ERR! Error: failed to fetch from registry: forever
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming](http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.12.28+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "forever" "-g"
npm ERR! cwd /
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: forever
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm not ok
pi@raspberrypi / $ 

As can be seen I am using Raspberry PI with Raspbian OS. Can someone help me?

**Comment by ssabareesh** [comment]
npm set registry http://registry.npmjs.org/
