### ISSUE TITLE
forever stop does not stop child processes

### ISSUE THREAD

**Issue by tjwebb** [foreversd/forever#621]
If I use something like `sudo -u` in my forever script, the `sudo` process is stopped but the actual process that I care about is still running after I `stop` it. Is there some way to kill the entire process group?

**Comment by sugir93** [comment]
function exitHandler(options, err) {
    console.log(err.stack);
    child_process.stop();
     process.exit();
}

//do something when app is closing
process.on('exit', exitHandler.bind(null,{cleanup:true}));

//catches ctrl+c event
process.on('SIGINT', exitHandler.bind(null, {exit:true}));

// catches "kill pid" (for example: nodemon restart)
process.on('SIGUSR1', exitHandler.bind(null, {exit:true}));
process.on('SIGUSR2', exitHandler.bind(null, {exit:true}));

//catches uncaught exceptions
process.on('uncaughtException', exitHandler.bind(null, {exit:true}));
