### ISSUE TITLE
Support multiple seperate node processes

### ISSUE THREAD

**Issue by codesplicer** [foreversd/forever#68]
I have 2 separate node apps hosted on the same server and would like forever to run and manage both of them. However it only runs one process at a time, and just kills the other when I try starting a new app.

**Comment by blu19234** [comment]
Hmm, it doesn't seem to work when the servers are in different directories.

If I do:

$ cd C:/Users/Me/Coding/Project1
$ forever start server.js
$ cd C:/Users/Me/Coding/Project2
$ forever start server.js

Then it doesn't work. I managed to get project2 to run like this, but project1 still won't run. Also, each server is running on it's own port and everything. Can anyone help, or I am I just doing something dumb?

**Comment by sibajeeray** [comment]
You can create a forever.json file in your root directory and mention all your ports there in that json file inside an array. Example:

### forever.json
```
[
   {
      "uid": "app1",
      "append": true,
      "watch": true,
      "script": "server.js",
      "sourceDir": "D:\\DEVELOPEMENT\\workshop",
      "args": ["--port", "8081", "--ip", "127.0.0.1"]
    },
    {

        "uid": "app2",
        "append": true,
        "watch": true,
        "script": "server.js",
        "sourceDir": "D:\\DEVELOPEMENT\\workshop" ,
        "args": ["--port", "8082", "--ip", "127.0.0.1"]
      },

      {

        "uid": "app3",
        "append": true,
        "watch": true,
        "script": "server.js",
        "sourceDir": "D:\\DEVELOPEMENT\\workshop" ,
        "args": ["--port", "8083", "--ip", "127.0.0.1"]
       }
]
```
Provide your source directory and script(app.js/server.js).

Now run all the above 3 apps in different ports by command **forever start forever.json**

But node forever pass ip and ports through command line to our program. So to get values from process.argv we need minimist package of node. install minimist and then write your app.js as below to provide ip and port dynamically through command(Forever will do it automatically).

### server.js / app.js
```
var express = require('express');
var app = express();

const parseArgs = require('minimist') (process.argv.slice(2))
const IP = parseArgs.ip || "127.0.0.1"
const PORT = parseArgs.port || 8000


app.get("/", function (req, res) {
  res.send("Server running on " + IP  + ":" + PORT)
})
console.log("START ", IP+" :",PORT)
app.listen(PORT, IP)

module.exports = app;
```
Now run forever start forever.json and check all the port described in forever.json.
