### ISSUE TITLE
cmd.exe popups when doing child_process.spawn

### ISSUE THREAD

**Issue by arve0** [foreversd/forever#732]
Hi!
On windows 8.1 child processes pops up when using forever and [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) inside node programs.

This snippet illustrates the problem:

```
var spawn = require("child_process").spawn

var p = spawn("ping", ["google.com"])

p.stdout.on("data", function(data){
  console.log(data.toString())
})

p.stderr.on("data", function(data){
  console.log(data.toString())
})

p.on("error", function(e){
  console.log(e)
})

p.on("close", function(code){
  console.log("timeout exited with code " + code)
})
```

Getting this result:
![skjermbilde](https://cloud.githubusercontent.com/assets/4810521/8735300/19aa627a-2c10-11e5-8c5e-3b0763fe0057.PNG)

This can get quite annoying if one is spawning a lot of childs, as the popups are brought to front and in focus.

**Comment by aliosv** [comment]
https://github.com/foreversd/forever/issues/767#issuecomment-502088605
