### ISSUE TITLE
Set name for process

### ISSUE THREAD

**Issue by jgallen23** [foreversd/forever#82]
It would be nice to set the name of the process since I use server.js for many of my projects and its tough to tell which process I need to stop/reset.  

```
info: Running action: list
info: Forever processes running
  [0] server.js [26824, 26823] /home/sites/.forever/BADz.log 0:13:20:19.44
  [1] server.js [14371, 14668] /home/sites/.forever/I916.log 3:22:3:6.329
```

Thoughts?

**Comment by dasdeck** [comment]
And why doesn't it work on one of my scripts?

**Comment by danday74** [comment]
www wwwwwwfdfd fd dhfdhdt hghgfhgfhdf

**Comment by denield** [comment]
>Now you can use the --pidFile option. Example:
>
>```
>forever start --pidFile /some/path/app1.pid app.js
>forever start --pidFile /some/path/app2.pid app.js
>```
>
>And to stop:
>```
>forever stop --pidFile /some/path/app1.pid
>```
>
[Source](https://stackoverflow.com/a/23836822)

**Comment by Ravonus** [comment]
I could not get --pidFile to close my file either. I also tried eval option and could not get it to work.
I figured the pid file is a simple file that keeps track of said PID for application/process within linux.

My simple fix was to just cat PID and use forever to close said number. Not sure if this helps anyone ha. Just came across this and was my fix. 

`forever stop $(cat /some/path/app.pid)`
