### ISSUE TITLE
Forever stop does not kill ts-node used with -c

### ISSUE THREAD

**Issue by lukasoppermann** [foreversd/forever#931]
Hey,

when I try to kill forever using `forever stopall` or `forever stop <pid>` one process remains active.

I am doing the following steps:
1. `forever start -v -c ts-node app.ts` I also tried using `--killSignal=SIGTERM`
2. 3 node instances are visible in the `activity monitor` one of which is the pid of forever (from `forever list`), one is the the pid under the section `pid` and one is another one (`pid` +1)
3. `forever stop <pid>` (forever and normal `pid` is stopped, but the `pid` +1 remains)

As a result my node app is still running, when I quit the last node process via the `activity monitor` my app stops running.

Some more info: `ts-node` starts 2 processes, when I run it like this in the terminal and kill it using `ctrl-c` both processes are killed. However, when it is killed via forever, the one process remains active. 

Can I provide any more info?

**Comment by seansfkelley** [comment]
I'm seeing this as well. Versions:

- CentOS 7
- Node 6.10.2
- forever 0.15.3
- ts-node 3.2.0

**Comment by dkladis** [comment]
I still have this issue! On Windows Server 2016, Node 10.15.0 and Forever 0.15.3...
